@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"D:\csf_formation c embarqué\common\bin\cspybat" "D:\csf_formation c embarqué\arm\bin\armproc.dll" "D:\csf_formation c embarqué\arm\bin\armsim2.dll"  %1 --plugin "D:\csf_formation c embarqué\arm\bin\armbat.dll" --macro "D:\csf_formation c embarqué\arm\config\debugger\ST\Trace_STM32F4xx.dmac" --backend -B "--endian=little" "--cpu=Cortex-M4" "--fpu=VFPv4" "-p" "D:\csf_formation c embarqué\arm\CONFIG\debugger\ST\iostm32f4xxx.ddf" "--semihosting" "--device=STM32F407VG" 


